sudo: required
language: node_js
node_js:
  - "8.9.1"
cache: yarn
install: npm install
script: "sudo $(which yarn) test"
before_script:
  - sudo apt-get update && sudo apt-get install yarn
  - chmod +x sh/build.sh
  - ./sh/build.sh
notifications:
  email: false
