sudo: required
language: node_js
node_js:
  - "7.10"
cache: yarn
install: npm install
script: "sudo $(which yarn) test"
before_script:
  - brew install yarn
  - chmod +x sh/build.sh
  - ./sh/build.sh
notifications:
  email: false
